version: "3.3"
services:
  db:
    image: mysql:5.7
    container_name: db
    restart: always
    environment:
      - MYSQL_DATABASE=monitor
      - MYSQL_USER=phpmyadmin
      - MYSQL_PASSWORD=deathnote
      - MYSQL_ROOT_PASSWORD=deathnote
      - TZ=America/Santiago
    ports:
      - "3307:3306"
    volumes:
      - my-db:/var/lib/mysql
    #volumes:
    #  - ~/mysql:/var/lib/mysql
    networks:
      - monitor-network
  php:
    container_name: php
    build: .
    #image: yiisoftware/yii2-php:7.2-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
      #- ./:/var/www/html:delegated
    ports:
      - "8080:80"
    networks:
      - monitor-network
volumes:
  my-db:
networks:
  monitor-network:
    driver: bridge
